### ISSUE TITLE
Pictures not optimized

### ISSUE THREAD

**Issue by DukeLim** [DukeLim/Ice-Magic#13]
![pictures](https://user-images.githubusercontent.com/111719582/203342012-9cd35982-4312-4bc9-9ac3-0b21434e0f26.jpg)
[Pictures.zip](https://github.com/DukeLim/Ice-Magic/files/10068376/Pictures.zip)

Use the pictures in the zip file.

**Comment by DuraiJuzApps** [comment]
updated
