### ISSUE TITLE
Booking Page - Ticket Type

### ISSUE THREAD

**Issue by DukeLim** [DukeLim/Ice-Magic#2]
![Mouseover](https://user-images.githubusercontent.com/111719582/201457782-075e2da6-e69a-4f53-9b5c-dc606fe0833f.jpg)

Based on Sistic site there are "i" info to be shown when mouse over for:
Child
Local Students
Senior Citizen

**Comment by DuraiJuzApps** [comment]
Done

**Comment by DuraiJuzApps** [comment]
Done
