### ISSUE TITLE
Payment Page - CC Number

### ISSUE THREAD

**Issue by DukeLim** [DukeLim/Ice-Magic#3]
https://user-images.githubusercontent.com/111719582/201458096-0256511a-0cab-4ae7-9eee-4c9dddc793fa.mp4

As shown in http://tnft-web-stage.s3-website-ap-southeast-1.amazonaws.com/payment 
by keying in the 1st 4 digits of the CC number website would be able to determine if it is a Visa, Master, ANEX etc and format the fields with relevant spacing. Should be a JS from Stripe, please explore.

![Stripe_JS](https://user-images.githubusercontent.com/111719582/201458193-de861ac3-764d-4b36-9e87-a24d55845afa.jpg)

**Comment by DuraiJuzApps** [comment]
Complete the changes
